- id: dockerfile-lint
  name: dockerfile-lint
  description: Lint Dockerfiles with hadolint
  entry: docker.pkg.github.com/virtualroot/pre-commit/pre-commit:latest hadolint
  language: docker_image
  types: [file]
  files: Dockerfile(.*)
