- id: dockerfile-lint
  name: dockerfile-lint
  description: Lint Dockerfiles with hadolint
  entry: virtualroot/pre-commit:latest hadolint
  language: docker_image
  types: [file]
  files: Dockerfile(.*)
- id: golang-staticcheck
  name: golang-staticcheck
  description: Lint Golang files with staticcheck
  entry: virtualroot/pre-commit:latest staticcheck
  language: docker_image
  types: [file]
  files: \.go$
  exclude: vendor\/.*$
- id: golang-golint
  name: golang-golint
  description: Lint Golang files with golint
  entry: virtualroot/pre-commit:latest fgt golint
  language: docker_image
  types: [file]
  files: \.go$
  exclude: vendor\/.*$
