- id: dockerfile-lint
  name: dockerfile-lint
  description: Lint Dockerfiles with hadolint
  entry: virtualroot/pre-commit:latest hadolint
  language: docker_image
  types: [file]
  files: Dockerfile(.*)
