name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install BATS
      run: sudo npm install -g bats

    - name: Setting up Python
      uses: actions/setup-python@v2

    - name: Setting up pre-commit
      run: pip install pre-commit

    - name: Runt Test
      run: npx bats test/

